name: test
on:
  push:
    branches:
      - latest
      - dev
      - patch-dev
  pull_request:
    
env:
  PRISMA_TELEMETRY_INFORMATION: "prisma-examples test.yaml"

jobs:
  
  # generate json for matrix via https://stackoverflow.com/a/62953566
  projects:
    if: github.repository_owner == 'prisma'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        
      - id: set-matrix
        run: |
          packages=$(find "." -not -path "*/node_modules/*" -type f -name "package.json")
          json=$(echo "$packages" | tr ' ' '\n' | jq -R -c)
          echo "::set-output name=project::$json"
    
  test:
    if: github.repository_owner == 'prisma'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:12-2.5-alpine
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testing
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - '5432:5432'

    strategy:
      matrix: ${{fromJson(needs.projects.outputs.matrix)}}
      
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          version: 12

      - name: test
        run: sh .github/scripts/test.sh ${{ matrix.project }}
        env:
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
